/**
 * GENERATED by `node tools/measure-events.mjs` — do not hand-edit.
 *
 * Where things actually HAPPEN in each embedded clip, found by sweeping it through a real
 * AnimationMixer at 240 Hz and reading the dynamics, not by scrubbing a timeline.
 *
 *   arrest   a limb travelling faster than 1.1 H/s that stops. Recorded at the frame of
 *            greatest DECELERATION, which is the frame the impact happens on — not the frame the
 *            limb was fastest, which is earlier, and not the frame it finally rests, which is later.
 *   plant    weight arriving: a foot below 0.14 H with its vertical velocity crossing from
 *            falling to still.
 *   driven   the body accelerated by something that is not its own limbs — a hip spike above
 *            9 H/s² with no limb arrest within 120 ms. This is what a blow TAKEN looks
 *            like from inside a clip.
 *
 * Everything is normalised to FIGURE HEIGHTS (H = 1.9 model units) and heights are
 * fractions of it, so the table survives a change of scale.
 *
 * `handPeak` and `bodyMean` are each clip's own motion budget. Continuous layers — trails, embers,
 * breath — are calibrated against them per clip: one global threshold smears the fast clips and
 * leaves the slow ones bare. The set spans handPeak 0.134 (fire) to 5.231 (box_02), a factor of 39.
 */

export interface ClipEvent {
  kind: 'arrest' | 'plant' | 'driven';
  bone: string;
  /** Seconds into the clip. */
  at: number;
  /** Deceleration in H/s² for an arrest or a driven spike. */
  decel?: number;
  /** Speed in H/s at the event. */
  speed?: number;
  /** Height above the ground as a fraction of figure height. */
  height?: number;
}

export interface ClipEvents {
  clip: string;
  duration: number;
  /** Fastest hand speed anywhere in the clip, H/s. */
  handPeak: number;
  /** Mean torso speed over the clip, H/s. */
  bodyMean: number;
  events: ClipEvent[];
}

export const FIGURE_HEIGHT = 1.9;

export const CLIP_EVENTS: Record<string, ClipEvents> = {
  'preset:biped:standing_relax': {
    clip: 'preset:biped:standing_relax', duration: 14.1, handPeak: 0.103, bodyMean: 0.006,
    events: [],
  },
  'preset:biped:box_01': {
    clip: 'preset:biped:box_01', duration: 1.8, handPeak: 2.201, bodyMean: 0.126,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.067, decel: 9.9 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.375, speed: 0.579, height: 0.13 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.433, decel: 87.2, speed: 0.442, height: 0.104 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.467, decel: 67.4, speed: 0.735, height: 0.609 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.1, decel: 60.7, speed: 0.485, height: 0.102 },
    ],
  },
  'preset:biped:box_02': {
    clip: 'preset:biped:box_02', duration: 2.267, handPeak: 5.231, bodyMean: 0.168,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.433, decel: 13.2 },
      { kind: 'plant', bone: 'R_ToeBase', at: 0.508, speed: 0.553, height: 0.081 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.667, decel: 219.1, speed: 0.767, height: 0.032 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.833, decel: 201.8, speed: 0.908, height: 0.581 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1, decel: 203.5, speed: 0.996, height: 0.06 },
      { kind: 'driven', bone: 'Hip', at: 1.133, decel: 14.6 },
      { kind: 'driven', bone: 'Hip', at: 1.333, decel: 24.3 },
      { kind: 'driven', bone: 'Hip', at: 1.633, decel: 44 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.8, decel: 70.7, speed: 0.472, height: 0.606 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.8, decel: 366.5, speed: 2.03, height: 0.687 },
    ],
  },
  'preset:biped:box_03': {
    clip: 'preset:biped:box_03', duration: 2.067, handPeak: 2.349, bodyMean: 0.129,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.3, decel: 9.3 },
      { kind: 'driven', bone: 'Hip', at: 0.533, decel: 24 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.55, speed: 0.712, height: 0.138 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.667, decel: 69, speed: 0.899, height: 0.628 },
      { kind: 'driven', bone: 'Hip', at: 0.867, decel: 9.1 },
    ],
  },
  'preset:biped:defeat_03': {
    clip: 'preset:biped:defeat_03', duration: 4.467, handPeak: 2.156, bodyMean: 0.177,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.4, decel: 9.2 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.812, speed: 0.621, height: 0.083 },
      { kind: 'driven', bone: 'Hip', at: 0.966, decel: 14.6 },
      { kind: 'plant', bone: 'R_ToeBase', at: 1.345, speed: 0.643, height: 0.108 },
      { kind: 'driven', bone: 'Hip', at: 1.632, decel: 10 },
      { kind: 'driven', bone: 'Hip', at: 2.131, decel: 9.4 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.602, decel: 103, speed: 0.906, height: 0.04 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.635, decel: 67.3, speed: 0.934, height: 0.022 },
      { kind: 'plant', bone: 'R_ToeBase', at: 2.926, speed: 0.68, height: 0.07 },
    ],
  },
  'preset:biped:fire': {
    clip: 'preset:biped:fire', duration: 1.233, handPeak: 0.134, bodyMean: 0.008,
    events: [],
  },
  'preset:biped:front_kick_01': {
    clip: 'preset:biped:front_kick_01', duration: 2.033, handPeak: 2.351, bodyMean: 0.303,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.033, decel: 14 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.267, decel: 142.4, speed: 0.167, height: 0.038 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.433, decel: 188.8, speed: 0.276, height: 0.407 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.6, decel: 168.4, speed: 0.992, height: 0.504 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.6, decel: 97.7, speed: 0.912, height: 0.576 },
      { kind: 'driven', bone: 'Hip', at: 0.767, decel: 9.6 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.9, decel: 142.1, speed: 0.983, height: 0.839 },
      { kind: 'driven', bone: 'Hip', at: 1.3, decel: 10.1 },
      { kind: 'plant', bone: 'R_ToeBase', at: 1.387, speed: 0.83, height: 0.139 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1.467, decel: 126.5, speed: 1.392, height: 0.104 },
      { kind: 'driven', bone: 'Hip', at: 1.633, decel: 18.7 },
      { kind: 'driven', bone: 'Hip', at: 1.867, decel: 54.7 },
    ],
  },
  'preset:biped:front_kick_02': {
    clip: 'preset:biped:front_kick_02', duration: 1.133, handPeak: 4.961, bodyMean: 0.542,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.033, decel: 46.9 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.267, decel: 88.4, speed: 0.372, height: 0.041 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.467, decel: 232, speed: 1.432, height: 0.003 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.833, decel: 122, speed: 2.992, height: 0.337 },
      { kind: 'plant', bone: 'R_ToeBase', at: 0.979, speed: 0.837, height: 0.139 },
      { kind: 'driven', bone: 'Hip', at: 1.067, decel: 17.3 },
    ],
  },
  'preset:biped:idle': {
    clip: 'preset:biped:idle', duration: 15.375, handPeak: 0.066, bodyMean: 0.006,
    events: [],
  },
};

/** The events of one clip, or an empty budget if it was never measured. */
export function clipEvents(clip: string): ClipEvents {
  return CLIP_EVENTS[clip] ?? { clip, duration: 0, handPeak: 0, bodyMean: 0, events: [] };
}

/** The single hardest stop in a clip — the frame worth building a move around. */
export function loudestArrest(clip: string): ClipEvent | null {
  const arrests = clipEvents(clip).events.filter((e) => e.kind === 'arrest');
  if (!arrests.length) return null;
  return arrests.reduce((a, b) => ((b.decel ?? 0) > (a.decel ?? 0) ? b : a));
}
