// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: house.glb  sha256=956e1e541af5551660b34255a1df30e81db10581e366192e70da55da47e69aea  bytes=7218544
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: "tripo_node_e3775a29-6a5b-4702-bf96-bf8600342791", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_e3775a29-6a5b-4702-bf96-bf8600342791",
  meshName: "tripo_mesh_e3775a29-6a5b-4702-bf96-bf8600342791",
  materialName: "tripo_material_e3775a29-6a5b-4702-bf96-bf8600342791",
  meshNodeWorldMatrix: [
      1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
    ],
  vertexCount: 73722,
  triangleCount: 112250,
  origin: [
      -0.3771716356277466,-0.3914947211742401,-0.49989429116249084
    ],
  extent: [
      0.7542930245399475,0.7830615043640137,0.9998926222324371
    ],
  bounds: { min: [
      -0.3771716356277466,-0.3914947211742401,-0.49989429116249084
    ], max: [
      0.3771213889122009,0.39156678318977356,0.4999983310699463
    ], extent: [
      0.7542930245399475,0.7830615043640137,0.9998926222324371
    ] },
  bytes: [442332,147444,221166,567420],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      81,53,39
    ],
  medianRoughness: 0.8588235294117647,
  medianMetalness: 0.023529411764705882,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "956e1e541af5551660b34255a1df30e81db10581e366192e70da55da47e69aea",
  sourceBytes: 7218544,
  route: "force-measured",
  codecHashes: {
    position: "54c626fb490a6cbec991fe6dbad18f32bb1c7d0dcdb879f8e0d397a00199f1a4",
    normal: "fa61590cda659bc3c17c0c8df422cef72761ca6f6b7c8c39b1d5894814641416",
    colour: "d67a56b2ab9e082a4c3dc94237f9d1068e54f28a658420af15da49785e1750dc",
    index: "89b6edbb8ff68646ab27a7376afa58a623b4d4fbdce0f8f63ffc3d8251d753fd",
    stream: "2ecce7dc243b832dd994c9047362b8be40583bc88fa5cc88364451e67846c6f7",
    base64: "3eeaf197b60044191c3b976c11d9055843af18f74ba828cbd5035ae20fe60c67",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 73722,
  sourceTriangleCount: 112250,
};

const STREAM_BYTES: number = 1378362;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-house-0.ts'),
    () => import('./chunks/island-surface-house-1.ts'),
    () => import('./chunks/island-surface-house-2.ts'),
    () => import('./chunks/island-surface-house-3.ts'),
    () => import('./chunks/island-surface-house-4.ts'),
    () => import('./chunks/island-surface-house-5.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/house: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/house: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/house: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/house: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Cabin");
}
