// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: dock.glb  sha256=3af0c9d3d91caa79eb37650430622923c6bab9b4fd8ed77d4f08428a19001125  bytes=6624684
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: "tripo_node_39d9865a-9ce6-4e18-b9ca-bef4e79daf08", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_39d9865a-9ce6-4e18-b9ca-bef4e79daf08",
  meshName: "tripo_mesh_39d9865a-9ce6-4e18-b9ca-bef4e79daf08",
  materialName: "tripo_material_39d9865a-9ce6-4e18-b9ca-bef4e79daf08",
  meshNodeWorldMatrix: [
      1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
    ],
  vertexCount: 72375,
  triangleCount: 115624,
  origin: [
      -0.24169932305812836,-0.17111438512802124,-0.49990713596343994
    ],
  extent: [
      0.4833699017763138,0.3422885984182358,0.9998779594898224
    ],
  bounds: { min: [
      -0.24169932305812836,-0.17111438512802124,-0.49990713596343994
    ], max: [
      0.24167057871818542,0.17117421329021454,0.49997082352638245
    ], extent: [
      0.4833699017763138,0.3422885984182358,0.9998779594898224
    ] },
  bytes: [434250,144750,217125,556804],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      135,83,50
    ],
  medianRoughness: 0.9568627450980393,
  medianMetalness: 0.00784313725490196,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "3af0c9d3d91caa79eb37650430622923c6bab9b4fd8ed77d4f08428a19001125",
  sourceBytes: 6624684,
  route: "force-measured",
  codecHashes: {
    position: "354e7d4484c6320daad986946a0e35614685c00b294ff887229bf3c062ddeb1e",
    normal: "9d6db6f5f3abeba24eb001f58da75bdee2fa8465e744cfc96cc67e91245a4fd4",
    colour: "8f46456ca5445aaa9f5bbb4e2f1e2b313e818e743ea3242f0fdd1c5d407e09c3",
    index: "c0a0e53acf3cbd4c2d808ae7321a31117cba8e01af49a420cb15b73a35970797",
    stream: "9e1978ae5733f5ea427d359ad89b204142d0f6ccd30c88cd217e31272a3ae205",
    base64: "1c744a0edfcc3ac5961b75077277e199dd98026a6b5802b5ec0e161c467319b6",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 72375,
  sourceTriangleCount: 115624,
};

const STREAM_BYTES: number = 1352929;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-dock-0.ts'),
    () => import('./chunks/island-surface-dock-1.ts'),
    () => import('./chunks/island-surface-dock-2.ts'),
    () => import('./chunks/island-surface-dock-3.ts'),
    () => import('./chunks/island-surface-dock-4.ts'),
    () => import('./chunks/island-surface-dock-5.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/dock: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/dock: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/dock: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/dock: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Dock");
}
