// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: barrel.glb  sha256=4a7badad31ae9fa28c89e723937d4002ab6b5d2edc8a467ea612a09ee1533c3f  bytes=7050616
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: null, matrix: [
      2.9764106921968465,0,0,0,0,2.9764106921968465,0,0,0,0,2.9764106921968465,0,-0.0001727952965617785,
      1.1000245266424535,-9.74412901811883e-05,1
    ], isMeshNode: false },
    { name: "tripo_node_10b972dc-231a-44fd-b995-cba8a138224b", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_10b972dc-231a-44fd-b995-cba8a138224b",
  meshName: null,
  materialName: "tripo_material_10b972dc-231a-44fd-b995-cba8a138224b",
  meshNodeWorldMatrix: [
      2.9764106921968465,0.0,0.0,0.0,0.0,2.9764106921968465,0.0,0.0,0.0,0.0,2.9764106921968465,0.0,
      -0.0001727952965617785,1.1000245266424535,-9.74412901811883e-05,1.0
    ],
  vertexCount: 59759,
  triangleCount: 104480,
  origin: [
      -0.4306849241256714,-0.313181072473526,-0.024313749745488167
    ],
  extent: [
      0.5315324515104294,0.682745486497879,0.5243120212107897
    ],
  bounds: { min: [
      -0.4306849241256714,-0.313181072473526,-0.024313749745488167
    ], max: [
      0.100847527384758,0.369564414024353,0.4999982714653015
    ], extent: [
      0.5315324515104294,0.682745486497879,0.5243120212107897
    ] },
  bytes: [358554,119518,179277,541451],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      107,74,36
    ],
  medianRoughness: 0.9176470588235294,
  medianMetalness: 0.01568627450980392,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "4a7badad31ae9fa28c89e723937d4002ab6b5d2edc8a467ea612a09ee1533c3f",
  sourceBytes: 7050616,
  route: "force-measured",
  codecHashes: {
    position: "929cf576de68e8f5715bed79af49449c5564e967f6da38a117733e96e615358e",
    normal: "6b285b62f7c2c5a7331abf705b74ded3eb2cda6e5873aa4b7b5bd151e0c8277a",
    colour: "92a7e8084c503fb8a636542bb41595c8031917b5e4b6dd166daebfd0ef990726",
    index: "1879e9ac2217042455ff5555afefeeb9d8059c5e6d3c76369ecf7ff1ca28abff",
    stream: "09c3d34cdea798c403234f6fa00c2277518394747b9e2310f958cde0bdbbc4d4",
    base64: "4f8daa61e5b0bdb9706b720aac82c464c27acfee2e4bc9e566d33c7a2627c73a",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 59759,
  sourceTriangleCount: 104480,
};

const STREAM_BYTES: number = 1198800;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-barrel-0.ts'),
    () => import('./chunks/island-surface-barrel-1.ts'),
    () => import('./chunks/island-surface-barrel-2.ts'),
    () => import('./chunks/island-surface-barrel-3.ts'),
    () => import('./chunks/island-surface-barrel-4.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/barrel: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/barrel: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/barrel: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/barrel: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Barrel");
}
