// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: crate.glb  sha256=c55ca44df8f6f96ddf108b52cc60ff0cc4769ef647ea8596126732f9c4135135  bytes=7046400
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: "tripo_node_c56046a4-77c5-47a1-8f5f-fa941c38fc25", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_c56046a4-77c5-47a1-8f5f-fa941c38fc25",
  meshName: "tripo_mesh_c56046a4-77c5-47a1-8f5f-fa941c38fc25",
  materialName: "tripo_material_c56046a4-77c5-47a1-8f5f-fa941c38fc25",
  meshNodeWorldMatrix: [
      1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
    ],
  vertexCount: 72307,
  triangleCount: 113734,
  origin: [
      -0.4999729096889496,-0.4663911461830139,-0.485787570476532
    ],
  extent: [
      0.9999729096889496,0.9326969087123871,0.9715085029602051
    ],
  bounds: { min: [
      -0.4999729096889496,-0.4663911461830139,-0.485787570476532
    ], max: [
      0.5,0.46630576252937317,0.4857209324836731
    ], extent: [
      0.9999729096889496,0.9326969087123871,0.9715085029602051
    ] },
  bytes: [433842,144614,216921,589971],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      155,98,56
    ],
  medianRoughness: 0.6235294117647059,
  medianMetalness: 0.00784313725490196,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "c55ca44df8f6f96ddf108b52cc60ff0cc4769ef647ea8596126732f9c4135135",
  sourceBytes: 7046400,
  route: "force-measured",
  codecHashes: {
    position: "e1331ee81d7039102760c6eb29dcdc5d0e3831c5247ca448733dc66037b78381",
    normal: "6fd11ee4b5763ee16d7c370c293dfdcbe2c57539435873b6ca18346f54224d60",
    colour: "91cdd5b491dbb879c79a6b2536e1917d24500e11547f0acafcb1c81a8e86a450",
    index: "2d98833fac35edcc5be3036d7ed00813c33af6cbd6ed76202850ac623ab6fb60",
    stream: "c80d85b01dab1db027ac7cbf284168c1084f5480d1d6bfc6a7689e7fe28e40c4",
    base64: "828bf3fb356254eff25ccd6b1063b415a155be3c3ff44412438ff5e33da005eb",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 72307,
  sourceTriangleCount: 113734,
};

const STREAM_BYTES: number = 1385348;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-crate-0.ts'),
    () => import('./chunks/island-surface-crate-1.ts'),
    () => import('./chunks/island-surface-crate-2.ts'),
    () => import('./chunks/island-surface-crate-3.ts'),
    () => import('./chunks/island-surface-crate-4.ts'),
    () => import('./chunks/island-surface-crate-5.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/crate: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/crate: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/crate: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/crate: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Crate");
}
