// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: boat.glb  sha256=7e21ec18aea6567df796d892f0dbdde637a8af7cdf6b179b195c0a319890bf4a  bytes=6279996
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: "tripo_node_4530fae6-8941-4b51-93b1-b90592e62826", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_4530fae6-8941-4b51-93b1-b90592e62826",
  meshName: "tripo_mesh_4530fae6-8941-4b51-93b1-b90592e62826",
  materialName: "tripo_material_4530fae6-8941-4b51-93b1-b90592e62826",
  meshNodeWorldMatrix: [
      1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
    ],
  vertexCount: 70538,
  triangleCount: 116566,
  origin: [
      -0.49998554587364197,-0.14462386071681976,-0.24213875830173492
    ],
  extent: [
      0.999985545873642,0.28931476175785065,0.4842357635498047
    ],
  bounds: { min: [
      -0.49998554587364197,-0.14462386071681976,-0.24213875830173492
    ], max: [
      0.5,0.14469090104103088,0.24209700524806976
    ], extent: [
      0.999985545873642,0.28931476175785065,0.4842357635498047
    ] },
  bytes: [423228,141076,211614,611637],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      94,58,34
    ],
  medianRoughness: 0.9411764705882353,
  medianMetalness: 0.01568627450980392,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "7e21ec18aea6567df796d892f0dbdde637a8af7cdf6b179b195c0a319890bf4a",
  sourceBytes: 6279996,
  route: "force-measured",
  codecHashes: {
    position: "df4724a778d5bdea5f1177b1e72be169c6487724f727d19e5dbc8fb979c86550",
    normal: "9c7f571bc1e8c7b46b745fab78b6ad0f5f6d2a500948a6fe82a2c2a398f2999b",
    colour: "7e32fa64eb7e04627a7042dafa9858747a2c00337f2976e1a895921c8b2ae048",
    index: "486af8ee4df65db027e140c25871b639d6e982ce72dd80e5f5f05c7386c412cc",
    stream: "8451afe0a778a17cf9e6027a1368542cfb150667a91cae5ba7f5e173b285072e",
    base64: "892dbce8bb2c197a7725805330ae885fdae93b75a919d0936f1ab05c6c284ff6",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 70538,
  sourceTriangleCount: 116566,
};

const STREAM_BYTES: number = 1387555;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-boat-0.ts'),
    () => import('./chunks/island-surface-boat-1.ts'),
    () => import('./chunks/island-surface-boat-2.ts'),
    () => import('./chunks/island-surface-boat-3.ts'),
    () => import('./chunks/island-surface-boat-4.ts'),
    () => import('./chunks/island-surface-boat-5.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/boat: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/boat: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/boat: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/boat: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Boat");
}
