// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: lamp.glb  sha256=9dd173d356df749c40cd31f8c650250aaebd8ced3f079326a0d249e6750381e8  bytes=5625640
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: "tripo_node_1053a718-3693-48c5-8808-a6d1f8fa0a17", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_1053a718-3693-48c5-8808-a6d1f8fa0a17",
  meshName: "tripo_mesh_1053a718-3693-48c5-8808-a6d1f8fa0a17",
  materialName: "tripo_material_1053a718-3693-48c5-8808-a6d1f8fa0a17",
  meshNodeWorldMatrix: [
      1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
    ],
  vertexCount: 65587,
  triangleCount: 114293,
  origin: [
      -0.10976848006248474,-0.4999987483024597,-0.328327476978302
    ],
  extent: [
      0.2195546105504036,0.9999894797801971,0.6566619277000427
    ],
  bounds: { min: [
      -0.10976848006248474,-0.4999987483024597,-0.328327476978302
    ], max: [
      0.10978613048791885,0.4999907314777374,0.3283344507217407
    ], extent: [
      0.2195546105504036,0.9999894797801971,0.6566619277000427
    ] },
  bytes: [393522,131174,196761,555335],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      126,76,37
    ],
  medianRoughness: 0.6235294117647059,
  medianMetalness: 0.011764705882352941,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "9dd173d356df749c40cd31f8c650250aaebd8ced3f079326a0d249e6750381e8",
  sourceBytes: 5625640,
  route: "force-measured",
  codecHashes: {
    position: "059a8454a420b14e2d966594e1ce34e522d9922898a900cfcb256f0a9a193166",
    normal: "1b69449d30805735c201314db2ae10cf624fcddd1214a42fce8f51c38a32ddc8",
    colour: "ac1d4cb18ede579c517a3e9efd6c25e8da52afc32fb32497bcff08601050fe75",
    index: "01270e6bff12c30c8584d428ded43fcdb5aec29d42244afc8345f2444d890c3f",
    stream: "445cd8bfff3277ac560d59844895d94510b84b0e6f9ca2004aec2c2d40ff9a3d",
    base64: "bf6b54f64e63edc499a5b94730f90bffb982faf6c5e74e4ec27e94f8d4b5fc16",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 65587,
  sourceTriangleCount: 114293,
  glassBounds: { min: [-0.034670066088438034,-0.06874559074640274,-0.26398974657058716] as const, max: [0.07850680500268936,0.06681890040636063,-0.15675269067287445] as const },
};

const STREAM_BYTES: number = 1276792;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-lamp-0.ts'),
    () => import('./chunks/island-surface-lamp-1.ts'),
    () => import('./chunks/island-surface-lamp-2.ts'),
    () => import('./chunks/island-surface-lamp-3.ts'),
    () => import('./chunks/island-surface-lamp-4.ts'),
    () => import('./chunks/island-surface-lamp-5.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/lamp: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/lamp: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/lamp: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/lamp: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Lamp");
}
