// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: red-rock.glb  sha256=9fe79668f4ff83dfa46da2e787533a91acc4b9955b975e240fba6fd2a1b178a1  bytes=6081824
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: "tripo_node_81fa628a-8692-498d-9be9-b64fd107d6a5", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_81fa628a-8692-498d-9be9-b64fd107d6a5",
  meshName: "tripo_mesh_81fa628a-8692-498d-9be9-b64fd107d6a5",
  materialName: "tripo_material_81fa628a-8692-498d-9be9-b64fd107d6a5",
  meshNodeWorldMatrix: [
      1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
    ],
  vertexCount: 71879,
  triangleCount: 114846,
  origin: [
      -0.4369051158428192,-0.3455451428890228,-0.4999937415122986
    ],
  extent: [
      0.8736759722232819,0.6910916864871979,0.9999937415122986
    ],
  bounds: { min: [
      -0.4369051158428192,-0.3455451428890228,-0.4999937415122986
    ], max: [
      0.43677085638046265,0.34554654359817505,0.5
    ], extent: [
      0.8736759722232819,0.6910916864871979,0.9999937415122986
    ] },
  bytes: [431274,143758,215637,590759],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      122,52,43
    ],
  medianRoughness: 0.9764705882352941,
  medianMetalness: 0.00392156862745098,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "9fe79668f4ff83dfa46da2e787533a91acc4b9955b975e240fba6fd2a1b178a1",
  sourceBytes: 6081824,
  route: "force-measured",
  codecHashes: {
    position: "ad9c119de5b2dff12eeab322c8f4b192c5084ed49ad9d304231d709e8d6d75f4",
    normal: "2aa497edc5cd2652c63c064309b41f182dfe37c287dc6df52cce043cb205c2d7",
    colour: "419218cdf0536c88cce46166cb4972b478149e3cfc3581d53424a4868e249d56",
    index: "89afd7b1eefd6f828903ca791e739c10e6e86d4dc228e4d47aa16a453c4691f2",
    stream: "b3e172f305a042c8c8c4162874cfa0a20f16fd89fc549df8a298e08271e57bc6",
    base64: "dee53b333bca7c50470ff74def70d7779a4944353299336c0f51ea416a4acdef",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 71879,
  sourceTriangleCount: 114846,
};

const STREAM_BYTES: number = 1381428;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-redRock-0.ts'),
    () => import('./chunks/island-surface-redRock-1.ts'),
    () => import('./chunks/island-surface-redRock-2.ts'),
    () => import('./chunks/island-surface-redRock-3.ts'),
    () => import('./chunks/island-surface-redRock-4.ts'),
    () => import('./chunks/island-surface-redRock-5.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/redRock: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/redRock: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/redRock: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/redRock: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Red rock island");
}
