// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Source: rocks.glb  sha256=e8c2e87d5d85e8d13d42595bd900478f774793fa83e64dd95d0826b0e7dfdf51  bytes=5538568
import * as THREE from 'three';
import {
  buildMeasuredSurface,
  decodeSurface,
  loadCompressedSurface,
  type DecodedSurface,
  type SurfaceEvidence,
  type SurfaceMeta,
} from './surfaceCodec';

export const surfaceMeta: SurfaceMeta = {
  version: 1,
  nodeChain: [
    { name: "tripo_node_e01b1b41-3e0c-4689-9873-b803f55c2222", matrix: [
      1.0,0.0,0.0,0,0.0,1.0,0.0,0,0.0,0.0,1.0,0,0.0,0.0,0.0,1
    ], isMeshNode: true },
  ],
  meshNodeName: "tripo_node_e01b1b41-3e0c-4689-9873-b803f55c2222",
  meshName: "tripo_mesh_e01b1b41-3e0c-4689-9873-b803f55c2222",
  materialName: "tripo_material_e01b1b41-3e0c-4689-9873-b803f55c2222",
  meshNodeWorldMatrix: [
      1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
    ],
  vertexCount: 69385,
  triangleCount: 118002,
  origin: [
      -0.49999380111694336,-0.3210357427597046,-0.4125976860523224
    ],
  extent: [
      0.9999490678310394,0.6421493589878082,0.8252370357513428
    ],
  bounds: { min: [
      -0.49999380111694336,-0.3210357427597046,-0.4125976860523224
    ], max: [
      0.49995526671409607,0.32111361622810364,0.4126393496990204
    ], extent: [
      0.9999490678310394,0.6421493589878082,0.8252370357513428
    ] },
  bytes: [416310,138770,208155,603885],
  baseColorFactor: [
      1.0,1.0,1.0,1.0
    ],
  roughnessFactor: 1.0,
  metalnessFactor: 1.0,
  alphaMode: "OPAQUE",
  alphaCutoff: 0.5,
  doubleSided: false,
  emissiveFactor: [
      0.0,0.0,0.0
    ],
  medianBaseColor: [
      92,102,118
    ],
  medianRoughness: 0.44313725490196076,
  medianMetalness: 0.00784313725490196,
  baseColorTextureTransform: { offset: [
      0.0,0.0
    ], scale: [
      1.0,1.0
    ], rotation: 0.0 },
  baseColorWrapS: 10497,
  baseColorWrapT: 10497,
  baseColorMinFilter: 9987,
  baseColorMagFilter: 9729,
  samplerFlipY: false,
  sourceSha256: "e8c2e87d5d85e8d13d42595bd900478f774793fa83e64dd95d0826b0e7dfdf51",
  sourceBytes: 5538568,
  route: "force-measured",
  codecHashes: {
    position: "57bc63d53f534710ca2a785caa362af684329bf6c31ea6cbcc6a2f5452c23288",
    normal: "229a5f9041d09701c4613a6f496044eecfb4dc2a41b9c45cd0b039a04d5a31c0",
    colour: "065c8816c7e59bd50f30d7ea988bc8eeff9a884cf6f08a0fab7bec756677a8b8",
    index: "488c2a097a9d6b5d60163516874d7a272c0a4dd0d0b609b74bf38c039807c7a2",
    stream: "f0d43e4103c7ede3255e41a3d4e9f452d54f1e8735f8274d63477aa47fc31027",
    base64: "ec78026cd6551bf8e79e70d32733fcabeaf7a0096f2f388241927ecd4eb1f421",
  },
};

export const surfaceEvidence: SurfaceEvidence = {
  sourceVertexCount: 69385,
  sourceTriangleCount: 118002,
};

const STREAM_BYTES: number = 1367120;

const CHUNK_LOADERS: ReadonlyArray<() => Promise<{ default: string }>> = [
    () => import('./chunks/island-surface-rocks-0.ts'),
    () => import('./chunks/island-surface-rocks-1.ts'),
    () => import('./chunks/island-surface-rocks-2.ts'),
    () => import('./chunks/island-surface-rocks-3.ts'),
    () => import('./chunks/island-surface-rocks-4.ts'),
    () => import('./chunks/island-surface-rocks-5.ts'),
];

let __bytes: Uint8Array | null = null;
let __prepare: Promise<void> | null = null;

export async function prepareRole(): Promise<void> {
  if (__bytes) return;
  if (__prepare) return __prepare;
  const p = (async () => {
    const buf = await loadCompressedSurface(CHUNK_LOADERS);
    if (buf.byteLength !== STREAM_BYTES) {
      throw new Error(`tropical-island/measured/rocks: decompressed byteLength ${buf.byteLength} != expected ${STREAM_BYTES}`);
    }
    __bytes = buf;
  })();
  __prepare = p;
  try { await p; }
  catch (e) { __prepare = null; throw e; }
}

export async function loadRoleBytes(): Promise<Uint8Array> {
  await prepareRole();
  if (!__bytes) throw new Error('tropical-island/measured/rocks: bytes unavailable after prepare');
  return __bytes;
}

export function decodeRoleSurface(): DecodedSurface {
  if (!__bytes) throw new Error('tropical-island/measured/rocks: not prepared; call prepareRole() first');
  return decodeSurface(surfaceMeta, __bytes);
}

export function buildRole(): THREE.Group {
  if (!__bytes) throw new Error('tropical-island/measured/rocks: not prepared; call prepareRole() first');
  return buildMeasuredSurface(surfaceMeta, __bytes, surfaceEvidence, "Gray shoreline boulders");
}
