// Auto-generated by pipelines/tropical-island/encode-surfaces.py
// Scene-owned prop factory. Each call constructs a fresh THREE.Group with measured
// geometry / material; no GLB / texture / UV is read at runtime.
import type * as THREE from 'three';

import { buildRole as build_house } from './data_house';
import { buildRole as build_palm } from './data_palm';
import { buildRole as build_dock } from './data_dock';
import { buildRole as build_boat } from './data_boat';
import { buildRole as build_rocks } from './data_rocks';
import { buildRole as build_redRock } from './data_redRock';
import { buildRole as build_crate } from './data_crate';
import { buildRole as build_barrel } from './data_barrel';
import { buildRole as build_campfire } from './data_campfire';
import { buildRole as build_lamp } from './data_lamp';

export type IslandPropRole = 'house' | 'palm' | 'dock' | 'boat' | 'rocks' | 'redRock' | 'crate' | 'barrel' | 'campfire' | 'lamp';

const ROLE_BUILD: Record<IslandPropRole, () => THREE.Group> = {
  house: build_house,
  palm: build_palm,
  dock: build_dock,
  boat: build_boat,
  rocks: build_rocks,
  redRock: build_redRock,
  crate: build_crate,
  barrel: build_barrel,
  campfire: build_campfire,
  lamp: build_lamp,
};

/** Build a fresh measured prop for the requested role. */
export function createMeasuredProp(role: IslandPropRole): THREE.Group {
  const build = ROLE_BUILD[role];
  if (!build) throw new Error(`tropical-island/measured/props: unknown role ${String(role)}`);
  return build();
}
