import { REGIONS } from './characterPalette';

/**
 * Who this character is, and what is actually known about her.
 *
 * Kept as data rather than prose in a README so the demo panel can show it beside the model, and so
 * every claim sits next to the thing that backs it. The distinction that matters here is between
 * what was MEASURED off the reconstruction, what was OBSERVED in the reference photograph, and what
 * was GENERATED by the tool that produced the mesh — a single photo cannot show a back, and saying
 * so is part of describing the character honestly.
 */

export type TagKind = 'subject' | 'palette' | 'craft' | 'vfx';

export interface CharacterTag {
  label: string;
  kind: TagKind;
  /** Why this tag is on her — shown as the chip's tooltip. */
  note: string;
}

/**
 * The tags that characterise her.
 *
 * Chosen to be things a reader could verify by looking: the period and role, the three colours the
 * whole design runs on, the ornament that repeats across every piece, and the techniques that make
 * the reconstruction what it is.
 */
export const TQ_TAGS: readonly CharacterTag[] = [
  { label: '三國 Three Kingdoms', kind: 'subject', note: 'Period and setting the armour design belongs to' },
  { label: 'female officer', kind: 'subject', note: 'Rank read from the cuirass, pauldrons and command sash rather than from a caption' },
  { label: 'lacquered plate', kind: 'subject', note: 'Layered lames over leather, not mail' },
  { label: 'dragon-and-cloud', kind: 'subject', note: 'The scrollwork motif repeated on cuirass, skirt, boots and belt buckle' },
  { label: 'phoenix-tail ribbon', kind: 'subject', note: 'The patterned headdress with two trailing tails' },
  { label: 'unarmed', kind: 'subject', note: 'She carries no weapon; the rig has no finger bones, so her blade is drawn as light instead' },

  { label: 'crimson', kind: 'palette', note: `Lacquer, measured ${REGIONS['lacquer-crimson'].measuredHex} at hue ${String(REGIONS['lacquer-crimson'].measuredHue)}°` },
  { label: 'gold', kind: 'palette', note: `Filigree, measured ${REGIONS['filigree-gold'].measuredHex} at hue ${String(REGIONS['filigree-gold'].measuredHue)}°` },
  { label: 'indigo', kind: 'palette', note: `Cloth and plate, measured ${REGIONS['cloth-indigo'].measuredHex} at hue ${String(REGIONS['cloth-indigo'].measuredHue)}°` },

  { label: 'code-only', kind: 'craft', note: 'No GLTF, OBJ or texture is fetched; geometry, rig and clips are embedded as source' },
  { label: '41-bone rig', kind: 'craft', note: 'Root "Root", nine levels deep, no finger bones' },
  { label: '24 clips', kind: 'craft', note: 'Retargeted presets, all measured to run; locomotion was corrected off Hip' },
  { label: '5 skinned meshes', kind: 'craft', note: 'One shared skeleton; the outfit is separate geometry from the body' },
  { label: 'recolourable', kind: 'craft', note: 'Each piece redyes by luminance, so the ornament survives the dye' },

  { label: '法陣 formation array', kind: 'vfx', note: 'Eight trigrams and seal script, inscribed outward' },
  { label: '神龍 spirit dragon', kind: 'vfx', note: 'Draws itself head-first along a helix' },
  { label: '綢帶 apsara silk', kind: 'vfx', note: 'Rope-solved ribbons that trail the hands and feet' },
  { label: '水墨 ink wash', kind: 'vfx', note: 'Ink that blooms and stalls, with gold sparks' },
  { label: '空間裂痕 air fracture', kind: 'vfx', note: 'Cracks walked as connected polylines' },
  { label: '焚身火焰 standing flame', kind: 'vfx', note: 'A ring of painted flame tongues around her' },
];

export interface ProfileEntry {
  label: string;
  value: string;
  /** Where the statement comes from, so a reader can weigh it. */
  source: 'measured' | 'observed' | 'generated';
}

/**
 * The detail sheet.
 *
 * `measured` means a number taken off the reconstruction by a probe or a gate. `observed` means it
 * is visible in the reference photograph. `generated` means the mesh tool invented it and no
 * reference confirms it — chiefly everything on her back and underside.
 */
export const TQ_PROFILE: readonly ProfileEntry[] = [
  { label: 'Subject', value: 'A Three Kingdoms officer, female, armoured for the field rather than for court', source: 'observed' },
  { label: 'Stature', value: '1.90 units tall, eight heads, athletic build', source: 'measured' },
  {
    label: 'Silhouette',
    value: 'Sleeveless lacquered cuirass; a skirt of layered plate lames front and back; close trousers; knee-high boots with a raised heel',
    source: 'observed',
  },
  {
    label: 'Armour',
    value: 'Crimson lacquer over leather with a clearcoat lobe; indigo dyed cloth backing steel lames; cast gold filigree at every border',
    source: 'observed',
  },
  {
    label: 'Ornament',
    value: 'Dragon-and-cloud scrollwork on cuirass, skirt panels and boot shafts; a dragon-head belt buckle at the waist; ruby studs across both pauldrons',
    source: 'observed',
  },
  {
    label: 'Head',
    value: 'Long black hair in a high ponytail falling past the waist; a patterned ribbon headdress with two trailing tails',
    source: 'observed',
  },
  {
    label: 'Hands',
    value: 'Empty. The rig gives each hand a single bone with no fingers, so nothing can be gripped — her blade is drawn as a brush stroke instead of modelled',
    source: 'measured',
  },
  {
    label: 'Palette',
    value: `crimson ${REGIONS['lacquer-crimson'].measuredHex} · gold ${REGIONS['filigree-gold'].measuredHex} · indigo ${REGIONS['cloth-indigo'].measuredHex} · skin ${REGIONS.skin.measuredHex} · hair ${REGIONS.hair.measuredHex}`,
    source: 'measured',
  },
  {
    label: 'Palette caveat',
    value: 'Those hexes carry the lighting the mesh was baked under, so they read darker than the reference. The hue is trustworthy; the level is not, which is why every effect colour is derived from hue and lifted',
    source: 'measured',
  },
  {
    label: 'Geometry',
    value: '294,240 triangles across 159,184 vertices, split into five skinned meshes — crimson 104,689 · indigo 59,067 · gold 59,882 · hair 50,625 · skin 19,977',
    source: 'measured',
  },
  {
    label: 'Rig',
    value: '41 bones from root "Root", nine levels at the deepest chain, no finger bones. All five meshes bind to one shared skeleton',
    source: 'measured',
  },
  {
    label: 'Animation',
    value: '24 retargeted clips, every one seeked and measured. Locomotion had been baked onto Hip rather than Root and dragged the figure up to 7.61 units off a 1.08-unit skeleton; that is corrected and the travel handed back separately',
    source: 'measured',
  },
  {
    label: 'Sockets',
    value: '10 anchors on real bones — two grips, six effect points, two ground contacts — each offset by a statistic taken from the skin that bone drives',
    source: 'measured',
  },
  {
    label: 'Hidden sides',
    value: 'Her back, her underside and the inside of every plate were invented by the mesh generator. One photograph cannot confirm them, and nothing here should be read as evidence about them',
    source: 'generated',
  },
  {
    label: 'Under the armour',
    value: 'Nothing. The source was a single closed surface, so hiding the costume reveals head, hair, arms and hands and no torso — that is a property of the measurement, not of the split',
    source: 'measured',
  },
];
