import { REGIONS } from './characterPalette';

/**
 * Who this character is.
 *
 * The panel shows the TAGS below; the fuller subject sheet at the foot of this file is source
 * documentation only and ships nothing. Both exist for the same reason: on a reconstruction made
 * from one photograph, what is known and how it came to be known are different questions, and the
 * second one is the harder of the two.
 */

export type TagKind = 'subject' | 'palette' | 'craft' | 'vfx';

export interface CharacterTag {
  label: string;
  kind: TagKind;
  /** Why this tag is on her — shown as the chip's tooltip. */
  note: string;
}

/**
 * The tags that characterise her.
 *
 * Chosen to be things a reader could verify by looking: the period and role, the three colours the
 * whole design runs on, the ornament that repeats across every piece, and the techniques that make
 * the reconstruction what it is.
 */
export const TQ_TAGS: readonly CharacterTag[] = [
  { label: '三國 Three Kingdoms', kind: 'subject', note: 'Period and setting the armour design belongs to' },
  { label: 'female officer', kind: 'subject', note: 'Rank read from the cuirass, pauldrons and command sash rather than from a caption' },
  { label: 'lacquered plate', kind: 'subject', note: 'Layered lames over leather, not mail' },
  { label: 'dragon-and-cloud', kind: 'subject', note: 'The scrollwork motif repeated on cuirass, skirt, boots and belt buckle' },
  { label: 'phoenix-tail ribbon', kind: 'subject', note: 'The patterned headdress with two trailing tails' },
  { label: 'unarmed', kind: 'subject', note: 'She carries no weapon; the rig has no finger bones, so her blade is drawn as light instead' },

  { label: 'crimson', kind: 'palette', note: `Lacquer, measured ${REGIONS['lacquer-crimson'].measuredHex} at hue ${String(REGIONS['lacquer-crimson'].measuredHue)}°` },
  { label: 'gold', kind: 'palette', note: `Filigree, measured ${REGIONS['filigree-gold'].measuredHex} at hue ${String(REGIONS['filigree-gold'].measuredHue)}°` },
  { label: 'indigo', kind: 'palette', note: `Cloth and plate, measured ${REGIONS['cloth-indigo'].measuredHex} at hue ${String(REGIONS['cloth-indigo'].measuredHue)}°` },

  { label: 'code-only', kind: 'craft', note: 'No GLTF, OBJ or texture is fetched; geometry, rig and clips are embedded as source' },
  { label: '41-bone rig', kind: 'craft', note: 'Root "Root", nine levels deep, no finger bones' },
  { label: '24 clips', kind: 'craft', note: 'Retargeted presets, all measured to run; locomotion was corrected off Hip' },
  { label: '5 skinned meshes', kind: 'craft', note: 'One shared skeleton; the outfit is separate geometry from the body' },
  { label: 'recolourable', kind: 'craft', note: 'Each piece redyes by luminance, so the ornament survives the dye' },

  { label: '法陣 formation array', kind: 'vfx', note: 'Eight trigrams and seal script, inscribed outward' },
  { label: '神龍 spirit dragon', kind: 'vfx', note: 'Draws itself head-first along a helix' },
  { label: '綢帶 apsara silk', kind: 'vfx', note: 'Rope-solved ribbons that trail the hands and feet' },
  { label: '水墨 ink wash', kind: 'vfx', note: 'Ink that blooms and stalls, with gold sparks' },
  { label: '空間裂痕 air fracture', kind: 'vfx', note: 'Cracks walked as connected polylines' },
  { label: '焚身火焰 standing flame', kind: 'vfx', note: 'A ring of painted flame tongues around her' },
];

/**
 * The subject sheet, kept as documentation rather than as shipped data.
 *
 * It was rendered in the demo panel for a while and has been taken out again; recording it here
 * costs the bundle nothing and keeps the reasoning with the code. The distinction that matters on a
 * single-photo reconstruction is not the statement but its provenance — MEASURED off the
 * reconstruction by a probe or gate, OBSERVED in the reference photograph, or GENERATED by the tool
 * that produced the mesh and confirmed by nothing.
 *
 *   Subject     [observed]  A Three Kingdoms officer, female, armoured for the field, not for court.
 *   Stature     [measured]  1.90 units, eight heads, athletic build.
 *   Silhouette  [observed]  Sleeveless lacquered cuirass; a skirt of layered plate lames front and
 *                           back; close trousers; knee-high boots with a raised heel.
 *   Armour      [observed]  Crimson lacquer over leather with a clearcoat lobe; indigo dyed cloth
 *                           backing steel lames; cast gold filigree at every border.
 *   Ornament    [observed]  Dragon-and-cloud scrollwork on cuirass, skirt panels and boot shafts; a
 *                           dragon-head belt buckle; ruby studs across both pauldrons.
 *   Head        [observed]  Long black hair in a high ponytail past the waist; a patterned ribbon
 *                           headdress with two trailing tails.
 *   Hands       [measured]  Empty. Each hand is a single bone with no fingers, so nothing can be
 *                           gripped — which is why her blade is drawn as a brush stroke.
 *   Palette     [measured]  crimson #5f2d21 · gold #ab8c55 · indigo #13182a · skin #bf977e ·
 *                           hair #13090e. These carry the lighting the mesh was baked under, so
 *                           they read darker than the reference: the hue is trustworthy, the level
 *                           is not, and every effect colour is derived from hue and lifted.
 *   Geometry    [measured]  294,240 triangles over 159,184 vertices, split five ways — crimson
 *                           104,689 · indigo 59,067 · gold 59,882 · hair 50,625 · skin 19,977.
 *   Rig         [measured]  41 bones from root "Root", nine levels at the deepest chain, no finger
 *                           bones. All five meshes bind to one shared skeleton.
 *   Animation   [measured]  24 retargeted clips, each seeked and measured. Locomotion had been baked
 *                           onto Hip rather than Root and dragged the figure up to 7.61 units off a
 *                           1.08-unit skeleton; corrected, with the travel handed back separately.
 *   Sockets     [measured]  10 anchors on real bones — two grips, six effect points, two ground
 *                           contacts — each offset by a statistic taken from the skin that bone drives.
 *   Hidden      [generated] Her back, her underside and the inside of every plate were invented by
 *                           the mesh generator. One photograph cannot confirm them.
 *   Underneath  [measured]  Nothing under the armour. The source was a single closed surface, so
 *                           hiding the costume reveals head, hair, arms and hands and no torso —
 *                           a property of the measurement, not of the split.
 */
